git:
  url:        https://github.com/microsoft/MeshGraphormer.git
  recursive:  True
pip:
  deps:
    - yacs
    - cython
    - nltk
    - scipy
    - 'numpy==1.23.1'
    - chumpy
    - boto3
    - requests
    - tqdm
    - opencv-python
    - matplotlib
  ignore_installed: True
  this_pkg_install_mode: develop
depend_on:
    - manopth
    - apex
    - opendr
data:
    gdown:
      - rel_path:       mano_model
        name:           MANO_LEFT.pkl
        url:            https://drive.google.com/file/d/1_IzjSTH1XSdQtPBVlzVHpXUk3pEkatYU/view?usp=sharing
        sym:
          src_rel:      MANO_LEFT.pkl
          target_rel:   src/modeling/data/MANO_LEFT.pkl
      - rel_path:       mano_model
        name:           MANO_RIGHT.pkl
        url:            https://drive.google.com/file/d/1q4UfbRDHmlkQmwRiGiStSdAQN5T8Odyc/view?usp=sharing
        sym:
          src_rel:      MANO_RIGHT.pkl
          target_rel:   src/modeling/data/MANO_RIGHT.pkl

    wget:
      - rel_path:       MeshGraphormer
        name:           graphormer_h36m_state_dict.bin
        url:            https://datarelease.blob.core.windows.net/metro/models/graphormer_h36m_state_dict.bin

      - rel_path:       MeshGraphormer
        name:           graphormer_3dpw_state_dict.bin
        url:            https://datarelease.blob.core.windows.net/metro/models/graphormer_3dpw_state_dict.bin

      - rel_path:       MeshGraphormer
        name:           graphormer_hand_state_dict.bin
        url:            https://datarelease.blob.core.windows.net/metro/models/graphormer_hand_state_dict.bin

      - rel_path:       hrnet
#        name:           hrnetv2_w64_imagenet_pretrained.pth
        url:            https://datarelease.blob.core.windows.net/metro/models/hrnetv2_w64_imagenet_pretrained.pth

      - rel_path:       hrnet
#        name:           cls_hrnet_w64_sgd_lr5e-2_wd1e-4_bs32_x100.yaml
        url:            https://datarelease.blob.core.windows.net/metro/models/cls_hrnet_w64_sgd_lr5e-2_wd1e-4_bs32_x100.yaml
