git:
  url: https://github.com/wyngjf/RAFT.git

pip:
  ignore_installed: True
  this_pkg_install_mode: develop

data:
  wget:
    - rel_path:       raft
      url:            https://www.dropbox.com/s/4j4z58wuv8o0mfz/models.zip
      unpack:         "jar -xvf models.zip"